# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_auto_20170430_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='collection.Profile'),
        ),
    ]
