# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-02 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_auto_20170501_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='city',
            name='restaurants',
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name_plural': 'restaurants'},
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(choices=[('florida', 'Florida'), ('texas', 'Texas'), ('california', 'California')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='collection.Profile'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
