# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-02 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_auto_20170502_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.CharField(choices=[('burguers', 'Burguers'), ('mexican', 'Mexican'), ('drinks', 'Drinks')], max_length=255, null=True),
        ),
    ]
