# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-02 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_restaurant_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
